// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson127273adDecodeAssetsCommonModel(in *jlexer.Lexer, out *Pageable) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "size":
			out.Size = int(in.Int())
		case "page":
			out.Page = int(in.Int())
		case "sort":
			if in.IsNull() {
				in.Skip()
				out.Sort = nil
			} else {
				if out.Sort == nil {
					out.Sort = new(Sort)
				}
				(*out.Sort).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson127273adEncodeAssetsCommonModel(out *jwriter.Writer, in Pageable) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Size))
	}
	{
		const prefix string = ",\"page\":"
		out.RawString(prefix)
		out.Int(int(in.Page))
	}
	if in.Sort != nil {
		const prefix string = ",\"sort\":"
		out.RawString(prefix)
		(*in.Sort).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Pageable) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson127273adEncodeAssetsCommonModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Pageable) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson127273adEncodeAssetsCommonModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Pageable) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson127273adDecodeAssetsCommonModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Pageable) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson127273adDecodeAssetsCommonModel(l, v)
}
