server:
  port: 8080

logging:
  level: debug
  dumpHttpRequest:
    enable: true
#    withBody: true

database:
  retryMaxTimeSec: 80
  postgres:
    host: localhost
    port: 5432
    database: graham
    username: assets
    password: assets
  redis:
    host: localhost
    port: 6379
#    dynamicPort: true
#    containerExpirationSec: 300
  jaeger:
    host: localhost
    port: 16686
    collectorHost: localhost
    collectorPort: 14268
#    dynamicPort: true
#    containerExpirationSec: 300

ldap:
  protocol: ldap
  host: localhost
  port: 1389
  baseDN: dc=deadline,dc=team
  username: cn=admin,dc=deadline,dc=team
  password: admin
  searchFilter: (&(objectClass=organizationalPerson)(mail=*)(title=*))
  searchWithSubtree: true
  userMapping:
    username: uid
    firstName: givenName
    lastName: sn
    email: mail
    position: title
    avatar: jpegPhoto
    phoneNumber: mobile

attachment:
  uploadPath: /Users/dnavetik/Desktop
