// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3b94576aDecodeAssetsModulesAssetModel(in *jlexer.Lexer, out *Asset) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "ownerId":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.OwnerID).UnmarshalText(data))
			}
		case "cityId":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.CityID).UnmarshalText(data))
			}
		case "name":
			out.Name = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "address":
			out.Address = string(in.String())
		case "incomes":
			if in.IsNull() {
				in.Skip()
				out.Incomes = nil
			} else {
				in.Delim('[')
				if out.Incomes == nil {
					if !in.IsDelim(']') {
						out.Incomes = make([]*CashFlow, 0, 8)
					} else {
						out.Incomes = []*CashFlow{}
					}
				} else {
					out.Incomes = (out.Incomes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *CashFlow
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(CashFlow)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Incomes = append(out.Incomes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "expenses":
			if in.IsNull() {
				in.Skip()
				out.Expenses = nil
			} else {
				in.Delim('[')
				if out.Expenses == nil {
					if !in.IsDelim(']') {
						out.Expenses = make([]*CashFlow, 0, 8)
					} else {
						out.Expenses = []*CashFlow{}
					}
				} else {
					out.Expenses = (out.Expenses)[:0]
				}
				for !in.IsDelim(']') {
					var v2 *CashFlow
					if in.IsNull() {
						in.Skip()
						v2 = nil
					} else {
						if v2 == nil {
							v2 = new(CashFlow)
						}
						(*v2).UnmarshalEasyJSON(in)
					}
					out.Expenses = append(out.Expenses, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b94576aEncodeAssetsModulesAssetModel(out *jwriter.Writer, in Asset) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	if true {
		const prefix string = ",\"ownerId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.RawText((in.OwnerID).MarshalText())
	}
	if true {
		const prefix string = ",\"cityId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.RawText((in.CityID).MarshalText())
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.Type != "" {
		const prefix string = ",\"type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Type))
	}
	if in.Address != "" {
		const prefix string = ",\"address\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Address))
	}
	if len(in.Incomes) != 0 {
		const prefix string = ",\"incomes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v3, v4 := range in.Incomes {
				if v3 > 0 {
					out.RawByte(',')
				}
				if v4 == nil {
					out.RawString("null")
				} else {
					(*v4).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	if len(in.Expenses) != 0 {
		const prefix string = ",\"expenses\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Expenses {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil {
					out.RawString("null")
				} else {
					(*v6).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Asset) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b94576aEncodeAssetsModulesAssetModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Asset) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b94576aEncodeAssetsModulesAssetModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Asset) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b94576aDecodeAssetsModulesAssetModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Asset) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b94576aDecodeAssetsModulesAssetModel(l, v)
}
